### ISSUE TITLE
Update release tag

### ISSUE THREAD

**Issue by m273d15** [WebFreak001/deploy-nightly#1]
I tried your action and it works great 👍 , but a bit different than expected.
I thought it would create a new release. Instead it uses an existing
release in order to provide the nightly releases as assets.

I like this approach, but this leads to the situation that the used release always points to an old commit. Do you support or want to support a method in the future that allows to update the tag of the release?

**Comment by WebFreak001** [comment]
hm yes the release tag will be buried under the other releases and the sources won't be accurate, however the advantage of having just one release tagged as nightly is that you can directly fetch from that tag in other applications doing automatic updates. (which is my use case why I made this extension too)

I would say for deleting the old release and creating a new one there should rather be a different action be used. Afterwards deploy-nightly can be used to automatically upload to it with the expected naming. Though then there isn't that much of an advantage over just directly uploading it. The action will currently automatically delete old releases and that doesn't make any sense with a freshly created tag. (e.g. only keep last 7 releases)

**Comment by m273d15** [comment]
Thanks, I will use the mentioned approach if I need a fresh release :+1:.
