### ISSUE TITLE
Request: Add generated asset name to output

### ISSUE THREAD

**Issue by kavsingh** [WebFreak001/deploy-nightly#12]
Hello! Thanks for this action 🙏 

Would be handy, for subsequent steps in some of my workflows, to be able to pick up the asset name generated by the action when using `$$`. essentially adding `"asset_name"` or such to the existing outputs here: https://github.com/WebFreak001/deploy-nightly/blob/master/index.js#L111-L112 .

Happy to open a PR for it. Thanks so much!

**Comment by WebFreak001** [comment]
sure, feel free to PR that
