### ISSUE TITLE
Running latest version creates a Node 12 warning in Github actions

### ISSUE THREAD

**Issue by ni-mkrieg** [WebFreak001/deploy-nightly#16]
I believe you need to change this in action.yml:
```runs:
  using: "node16"
```

>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16...

**Comment by WebFreak001** [comment]
fixed in https://github.com/WebFreak001/deploy-nightly/commit/038574a6c64046ecaca622ef3d83134964d31033
