### ISSUE TITLE
What is the link to the uploaded asset

### ISSUE THREAD

**Issue by cdcseacave** [WebFreak001/deploy-nightly#17]
Stupid question, I used your action to upload the build binaries, it seems to be working, thank you, but from where do I get the uploaded asset? Can the action print the final link to the uploaded asset?

**Comment by WebFreak001** [comment]
the following things are output by the action:

https://github.com/WebFreak001/deploy-nightly/blob/b2651b28edc94c14f10c169905cd2aa84c75037d/index.js#L111-L113

If you give the deploy-nightly step an id, you can output it e.g. using
```
echo ${{steps.<id>.outputs.url}}
```

**Comment by cdcseacave** [comment]
thank you
