### ISSUE TITLE
Delete before upload

### ISSUE THREAD

**Issue by Guite** [WebFreak001/deploy-nightly#2]
Hello,
I want to use your action for updating one file which always has the same file name. But this currently fails with the following error:
```
##[error]Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
##[error]Node run failed with exit code 1
```
From looking at your source code it seems you are first uploading the new asset and removing old assets afterwards. Would it be possible to delete old files first?

**Comment by Guite** [comment]
Proposed change: https://github.com/Guite/deploy-nightly/commit/63dc73628423feeea196dc8ad22dc86c903d86b7
(works for me)

**Comment by WebFreak001** [comment]
hm this should never happen because it checks for an existing asset in line 67

Can you share your Github Actions configuration of deploy-nightly where this happens? (asset_name and max_releases especially)

**Comment by Guite** [comment]
Of course:

* [Release](https://github.com/Guite/MostGenerator/releases/tag/standalone)
* [Workflow definition](https://github.com/Guite/MostGenerator/blob/master/.github/workflows/build-component.yml#L58-L71)
* [Failing workflow run](https://github.com/Guite/MostGenerator/commit/3ae1918b50294ac008977a728cc6b4e937cf1318/checks?check_suite_id=348691260)

**Comment by WebFreak001** [comment]
oh I see, without the hashes it does fail when trying to upload a new asset.

However I think deleting after uploading is a lot safer, so this should get a special case when the target filename is already in the list of uploaded assets.

**Comment by Guite** [comment]
Anything I can/should do in order to workaround or otherwise proceed? What do you suggest?

**Comment by WebFreak001** [comment]
this isn't really the use-case of this extension anyway (not having hash and date) because the official actions extension could do that too, but I have fixed it now for version `v1.0.2`

**Comment by Guite** [comment]
> the official actions extension could do that too

Which one do you refer to?

> I have fixed it now

Thanks! Going to check it out.

**Comment by WebFreak001** [comment]
https://github.com/actions/upload-release-asset

but actually not too sure what it does with existing files, so this might actually be working better with my extension here.

**Comment by Guite** [comment]
Indeed. There is an unsolved issue there about overwriting assets. So I will happily use your action instead. Thanks again :-)
