### ISSUE TITLE
update to node20 required

### ISSUE THREAD

**Issue by jens-maus** [WebFreak001/deploy-nightly#28]
In September 2023, GitHub has announced that all nodejs-dependent github actions require to update to nodejs v20 since nodejs v16 is EOL. See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Since a few weeks all GitHub workflows where such actions are used are now returning warning and support for nodejs v16 actions are about to be cancelled in spring 2024. So please update this action to use nodejs v20 ASAP.

**Comment by n-elie** [comment]
I made the changes in https://github.com/n-elie/deploy-nightly/tree/master and it seems to work out of the box: https://github.com/n-elie/deploy-nightly/actions/runs/7831213010

**Comment by jens-maus** [comment]
> I made the changes in https://github.com/n-elie/deploy-nightly/tree/master and it seems to work out of the box: https://github.com/n-elie/deploy-nightly/actions/runs/7831213010

Then submit a Pull Request to @WebFreak001 so that he can incorporate your changes because nobody wants to switch to a different fork just because of that tiny change here :)

**Comment by n-elie** [comment]
I did not submit a PR because I add to change the test workflow to make it work with this fork.
This was just to confirm that this one line change works

**Comment by WebFreak001** [comment]
fixed by 7fb3a649e6b8b2173c1a370a7196078c43dc2262
