### ISSUE TITLE
3.1.0 unhandled throw on node:events:492

### ISSUE THREAD

**Issue by i-make-robots** [WebFreak001/deploy-nightly#29]
Project with issue is https://github.com/MarginallyClever/Makelangelo-software/
Previously using deply-nightly:2.0.0.  
The action builds the universal java package, then creates a nightly version for each supported platform.  At this point the system fails.
Possibly related to https://github.com/actions/runner-images/issues/9741
Action error is:
```
Run WebFreak001/deploy-nightly@v3.1.0
Checking previous assets
Queuing old asset Makelangelo-nightly-20240527-a277fb.dmg for deletion
Uploading asset as file Makelangelo-nightly-20240530-66b481.dmg
Error: Resource not accessible by integration
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.8.1
```

Any ideas what I can do to fix this?

**Comment by WebFreak001** [comment]
> Resource not accessible by integration

sounds like the access token is missing permissions. 

looking at your action you are running it unconditionally also in pull requests:

https://github.com/MarginallyClever/Makelangelo-software/blob/a277fb96bcaace90e354097c2c0b39063cb1f11e/.github/workflows/maven.yml#L129-L141

Pull requests are run in a separate security scope with the token by github (e.g. in the repository of the PR author), causing it to fail when trying to upload a file.

Additionally if that doesn't fix your issue, try adding permissions, e.g. explicitly giving it `permission: write-all` to test it out. See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by i-make-robots** [comment]
Thank you for the quick response!

Hmm... the linked Action version is a bit out of date, I used `with.token` instead of `env.token`.  I added `with.permission=write-all` and it's still failing. :(

**Comment by WebFreak001** [comment]
`with.token` is the new way, but you don't need to specify it (it takes it by default)

**Comment by WebFreak001** [comment]
oh yeah and please upgrade to v3

**Comment by i-make-robots** [comment]
upgrade what?  I'm already using 3.1.0?

**Comment by i-make-robots** [comment]
the maven.yml used is the one from the PR.  You might be looking at the master branch.

**Comment by i-make-robots** [comment]
What?  No...  It looks like you're telling me to update my maven.yml while referencing the master branch, which uses deploy-nightly:2.0.0.  I'm referencing the one in the PR on the same project, the one that's being used in the Action, which is using deploy-nightly:3.1.0.

**Comment by i-make-robots** [comment]
Oh heck!  I'm so sorry.  It's working on the master branch now.  Thank you!

How would I get the Action to give me a meaningful error message so that, in future, I remember this is the cause?

**Comment by WebFreak001** [comment]
hm I can hint to a discussion, but the error comes from the github API and may change depending on what kind of token you provide and how exactly you call the action.

The action here might have worked for example if the repo owner & release id were matching on the PR author's repository (since it would then instead upload there)

**Comment by i-make-robots** [comment]
yeah, most PRs are me modding my own stuff, no issue.
